# Generated by Django 3.1.2 on 2021-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paddock', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Pest', models.CharField(choices=[('AW', 'Armyworm'), ('CL', 'Cabbage Looper'), ('CEW', 'Corn Earworm'), ('SJS', 'San Jose Scale'), ('TSM', 'Two Spotted Mite')], max_length=20)),
                ('GDD_Today', models.IntegerField()),
                ('GDD_Acumulated', models.IntegerField()),
                ('Stage', models.IntegerField()),
                ('T_min_celsius', models.IntegerField()),
                ('T_max_celsius', models.IntegerField()),
                ('Weather_station', models.CharField(max_length=20)),
            ],
        ),
    ]
