# Generated by Django 3.1.2 on 2021-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='GDD_Acumulated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='GDD_Today',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Stage',
            field=models.IntegerField(null=True),
        ),
    ]
