# Generated by Django 3.1.2 on 2021-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0002_auto_20210425_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='GDD_Acumulated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='GDD_Today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='T_max_celsius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='T_min_celsius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
