# Generated by Django 3.1.2 on 2021-04-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0003_auto_20210425_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='Stage',
        ),
        migrations.AddField(
            model_name='tracker',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='warning',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Pest',
            field=models.CharField(choices=[('Armyworm', 'Armyworm'), ('Cabbage Looper', 'Cabbage Looper'), ('Corn Earworm', 'Corn Earworm'), ('San Jose Scale', 'San Jose Scale'), ('Two Spotted Mite', 'Two Spotted Mite')], max_length=20),
        ),
    ]
