# Generated by Django 3.1.2 on 2021-04-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0004_auto_20210425_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
