# Generated by Django 3.1.2 on 2021-04-26 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0005_auto_20210425_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='Weather_station',
        ),
        migrations.AddField(
            model_name='tracker',
            name='Farm_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='Nearest_location',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Bonanza', 'Bonanza'), ('Bouganvilia', 'Bouganvilia'), ('Cengicaña', 'Cengicaña'), ('Costa Brava', 'Costa Brava'), ('El Balsamo', 'El Balsamo'), ('Escuintla Irlanda', 'Escuintla Irlanda'), ('La Giralta', 'La Giralta'), ('Mazaten Ango San Nico', 'Mazaten Ango San Nico'), ('Naranjales', 'Naranjales'), ('Petén oficina', 'Petén oficina'), ('Puyumate', 'Puyumate'), ('Retalhuleu Xoluta', 'Retalhuleu Xoluta'), ('San Antonio del Valle', 'San Antonio del Valle'), ('San Rafael', 'San Rafael'), ('Santa Rosa La candelaria', 'Santa Rosa La candelaria'), ('Tehuantepeq', 'Tehuantepeq')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
