# Generated by Django 3.1.2 on 2021-05-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0006_auto_20210426_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Farm_name', models.CharField(max_length=40)),
                ('Paddock', models.CharField(max_length=10)),
                ('T_min_celsius', models.IntegerField()),
                ('T_max_celsius', models.IntegerField()),
                ('GDD_Today', models.IntegerField()),
                ('GDD_Acumulated', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='GDD_Acumulated',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='GDD_Today',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='T_max_celsius',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='T_min_celsius',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Nearest_location',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Bonanza', 'Bonanza'), ('Bouganvilia', 'Bouganvilia'), ('Cengicaña', 'Cengicaña'), ('Costa Brava', 'Costa Brava'), ('El Balsamo', 'El Balsamo'), ('Escuintla Irlanda', 'Escuintla Irlanda'), ('La Giralta', 'La Giralta'), ('Mazatenango San Nico', 'Mazatenango San Nico'), ('Naranjales', 'Naranjales'), ('Petén oficina', 'Petén oficina'), ('Puyumate', 'Puyumate'), ('Retalhuleu Xoluta', 'Retalhuleu Xoluta'), ('San Antonio del Valle', 'San Antonio del Valle'), ('San Rafael', 'San Rafael'), ('Santa Rosa La candelaria', 'Santa Rosa La candelaria'), ('Tehuantepeq', 'Tehuantepeq')], max_length=40),
        ),
    ]
