# Generated by Django 3.1.2 on 2021-05-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDD_tracker', '0008_tracker_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='Farm_name',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='Paddock',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='Farm_name',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='Paddock',
        ),
        migrations.AddField(
            model_name='dates',
            name='Nearest_location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='dates',
            name='Pest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
